import { useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import * as DocumentPicker from 'expo-document-picker';
import { File } from 'expo-file-system';
import { ArrowLeft, FileText, Lightbulb, Sparkles, Upload } from 'lucide-react-native';
import { ApiError, createProject, parseDocumentFile, suggestGenre } from '@/lib/api';
import { saveLocalProject, type LocalProject } from '@/lib/storage';

const lime = '#d5f36a';
const durations = [
  { label: '30 sec', seconds: 30 },
  { label: '1 min', seconds: 60 },
  { label: '3 min', seconds: 180 },
  { label: '5 min', seconds: 300 },
  { label: '10 min', seconds: 600 },
  { label: '20 min', seconds: 1200 },
  { label: '30 min', seconds: 1800 },
];
const genres = ['Romance', 'Action', 'Adventure', 'Comedy', 'Drama', 'Horror', 'Thriller', 'Sci-Fi', 'Fantasy', 'Mystery', 'Documentary', 'Custom'];
const languages = ['English', 'Vietnamese', 'Chinese', 'Japanese', 'Korean', 'Spanish', 'French', 'German', 'Portuguese', 'Thai', 'Indonesian', 'Hindi', 'Arabic'];
const formats = ['16:9', '9:16', '1:1', '4:5'] as const;
const resolutions = ['720p', '1080p', '4k'] as const;
const frameRates = [24, 25, 30, 60] as const;

export default function CreateScreen() {
  const router = useRouter();
  const { source } = useLocalSearchParams<{ source?: string }>();
  const [title, setTitle] = useState('');
  const [story, setStory] = useState('');
  const [genre, setGenre] = useState('Drama');
  const [customGenre, setCustomGenre] = useState('');
  const [format, setFormat] = useState<LocalProject['format']>('16:9');
  const [duration, setDuration] = useState(60);
  const [language, setLanguage] = useState('English');
  const [tone, setTone] = useState('Cinematic');
  const [visualStyle, setVisualStyle] = useState('Cinematic realism');
  const [resolution, setResolution] = useState<NonNullable<LocalProject['resolution']>>('720p');
  const [fps, setFps] = useState<NonNullable<LocalProject['fps']>>(24);
  const [busy, setBusy] = useState(false);
  const [importing, setImporting] = useState(false);
  const [suggesting, setSuggesting] = useState(false);
  const [genreReason, setGenreReason] = useState('');

  async function importDocument() {
    setImporting(true);
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: ['text/plain', 'application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
        copyToCacheDirectory: true,
        multiple: false,
      });
      const asset = result.assets?.[0];
      if (result.canceled || !asset) return;
      try {
        const parsed = await parseDocumentFile({ uri: asset.uri, name: asset.name, mimeType: asset.mimeType });
        setStory(parsed.text);
        setTitle((current) => current || asset.name.replace(/\.[^.]+$/, ''));
        Alert.alert('Document imported', `${parsed.chapters.length} chapter sections · ${parsed.characterCount.toLocaleString()} characters`);
      } catch (error) {
        if (/\.(txt|md)$/i.test(asset.name)) {
          const text = await new File(asset.uri).text();
          setStory(text);
          setTitle((current) => current || asset.name.replace(/\.[^.]+$/, ''));
          Alert.alert('Text imported locally', 'This document was read on this device. PDF/DOCX parsing requires the configured API.');
        } else {
          throw error;
        }
      }
    } catch (error) {
      Alert.alert('Could not import document', error instanceof Error ? error.message : 'Choose a TXT, PDF or DOCX file.');
    } finally {
      setImporting(false);
    }
  }

  async function recommendGenre() {
    if (!story.trim()) {
      Alert.alert('Add a story first', 'Genre recommendations use your story text.');
      return;
    }
    setSuggesting(true);
    try {
      const result = await suggestGenre(story.trim(), title.trim() || 'Untitled');
      setGenre(result.genre);
      setGenreReason(`${result.demo ? 'DEMO recommendation' : 'AI recommendation'}: ${result.reason}`);
    } catch {
      const text = story.toLowerCase();
      const recommendation = /murder|mystery|detective|clue/.test(text) ? 'Mystery'
        : /space|planet|robot|future|spaceship/.test(text) ? 'Sci-Fi'
          : /ghost|haunted|nightmare|demon/.test(text) ? 'Horror'
            : /battle|warrior|fight|chase/.test(text) ? 'Action'
              : /love|heart|romance|wedding/.test(text) ? 'Romance' : 'Drama';
      setGenre(recommendation);
      setGenreReason('DEMO recommendation: suggested from story keywords; not generated by an AI provider.');
    } finally {
      setSuggesting(false);
    }
  }

  async function create() {
    if (!title.trim() || !story.trim()) {
      Alert.alert('A little more to work with', 'Add a title and your story or idea to begin.');
      return;
    }
    const selectedGenre = genre === 'Custom' ? customGenre.trim() : genre;
    if (!selectedGenre) {
      Alert.alert('Name your genre', 'Enter a custom genre or choose one of the listed genres.');
      return;
    }
    setBusy(true);
    const draft = {
      title: title.trim(), story: story.trim(), genre: selectedGenre, format, durationSeconds: duration,
      language, audience: 'General', tone, visualStyle, resolution, fps,
    };
    let project: LocalProject;
    try {
      const result = await createProject(draft);
      project = { ...result.project, ...draft, updatedAt: new Date().toISOString(), status: 'DRAFT' };
    } catch (error) {
      if (error instanceof ApiError || !(error instanceof TypeError)) {
        Alert.alert('Project was not created', error instanceof Error ? error.message : 'The API rejected this project.');
        setBusy(false);
        return;
      }
      project = { id: `demo-${Date.now()}`, ...draft, updatedAt: new Date().toISOString(), status: 'DRAFT' };
    }
    try {
      await saveLocalProject(project);
      router.replace(`/projects/${project.id}`);
    } catch {
      Alert.alert('Could not save project', 'Please check the available storage on this device.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      <Pressable style={styles.back} onPress={() => router.back()}>
        <ArrowLeft size={18} color="#e9e9df" /><Text style={styles.backText}>STUDIO</Text>
      </Pressable>
      <Text style={styles.eyebrow}>NEW PROJECT {source ? `· ${source.toUpperCase()}` : ''}</Text>
      <Text style={styles.title}>Start with{'\n'}a <Text style={{ color: lime }}>story.</Text></Text>
      <Text style={styles.subtitle}>Drop in a story, a scene, or one good idea. We’ll build the film around it.</Text>

      <View style={styles.field}>
        <Text style={styles.label}>PROJECT TITLE</Text>
        <TextInput value={title} onChangeText={setTitle} placeholder="The name of your film" placeholderTextColor="#70766f" style={styles.input} maxLength={100} />
      </View>
      <View style={styles.field}>
        <View style={styles.labelLine}><Text style={styles.label}>YOUR STORY</Text><Text style={styles.optional}>IDEA · STORY · SCREENPLAY</Text></View>
        <TextInput value={story} onChangeText={setStory} placeholder="A lighthouse keeper finds a message in a bottle..." placeholderTextColor="#70766f" multiline textAlignVertical="top" style={[styles.input, styles.storyInput]} maxLength={500000} />
        <View style={styles.inputFooter}>
          <Text style={styles.counter}>{story.length.toLocaleString()} / 500,000</Text>
          <Pressable style={styles.importButton} onPress={() => void importDocument()} disabled={importing}>
            {importing ? <ActivityIndicator size="small" color={lime} /> : <Upload size={13} color={lime} />}
            <Text style={styles.importText}>{importing ? 'Reading...' : 'Import TXT / PDF / DOCX'}</Text>
          </Pressable>
        </View>
      </View>

      <View style={styles.sectionRow}>
        <Text style={styles.label}>GENRE</Text>
        <Pressable onPress={() => void recommendGenre()} disabled={suggesting} style={styles.suggestButton}>
          {suggesting ? <ActivityIndicator size="small" color={lime} /> : <Sparkles size={12} color={lime} />}
          <Text style={styles.suggestText}>{suggesting ? 'Suggesting' : 'Suggest genre'}</Text>
        </Pressable>
      </View>
      <View style={styles.chips}>{genres.map((item) => (
        <Pressable key={item} onPress={() => setGenre(item)} style={[styles.chip, genre === item && styles.chipActive]}>
          <Text style={[styles.chipText, genre === item && styles.chipTextActive]}>{item}</Text>
        </Pressable>
      ))}</View>
      {genre === 'Custom' && <TextInput value={customGenre} onChangeText={setCustomGenre} placeholder="Name your genre" placeholderTextColor="#70766f" style={[styles.input, styles.optionInput]} maxLength={80} />}
      {genreReason ? <Text style={styles.recommendation}>{genreReason}</Text> : null}

      <Text style={styles.label}>LANGUAGE</Text>
      <View style={styles.chips}>{languages.map((item) => (
        <Pressable key={item} onPress={() => setLanguage(item)} style={[styles.chip, language === item && styles.chipActive]}>
          <Text style={[styles.chipText, language === item && styles.chipTextActive]}>{item}</Text>
        </Pressable>
      ))}</View>
      <Text style={styles.label}>TONE</Text>
      <TextInput value={tone} onChangeText={setTone} placeholder="Warm, suspenseful, lyrical..." placeholderTextColor="#70766f" style={[styles.input, styles.optionInput]} maxLength={300} />
      <Text style={styles.label}>VISUAL STYLE</Text>
      <TextInput value={visualStyle} onChangeText={setVisualStyle} placeholder="Cinematic realism, watercolor..." placeholderTextColor="#70766f" style={[styles.input, styles.optionInput]} maxLength={300} />

      <View style={styles.labelLine}><Text style={styles.label}>FRAME</Text><Text style={styles.optional}>CHANGE ANYTIME</Text></View>
      <View style={styles.chips}>{formats.map((item) => (
        <Pressable key={item} onPress={() => setFormat(item)} style={[styles.chip, styles.frameChip, format === item && styles.chipActive]}>
          <Text style={[styles.chipText, format === item && styles.chipTextActive]}>{item}</Text>
        </Pressable>
      ))}</View>
      <Text style={styles.label}>TARGET LENGTH</Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.durationList}>{durations.map((item) => (
        <Pressable key={item.seconds} onPress={() => setDuration(item.seconds)} style={[styles.durationChip, duration === item.seconds && styles.chipActive]}>
          <Text style={[styles.chipText, duration === item.seconds && styles.chipTextActive]}>{item.label}</Text>
        </Pressable>
      ))}</ScrollView>
      <Text style={styles.label}>RESOLUTION</Text>
      <View style={styles.chips}>{resolutions.map((item) => (
        <Pressable key={item} onPress={() => setResolution(item)} style={[styles.chip, resolution === item && styles.chipActive]}>
          <Text style={[styles.chipText, resolution === item && styles.chipTextActive]}>{item.toUpperCase()}</Text>
        </Pressable>
      ))}</View>
      <Text style={styles.label}>FRAME RATE</Text>
      <View style={styles.chips}>{frameRates.map((item) => (
        <Pressable key={item} onPress={() => setFps(item)} style={[styles.chip, fps === item && styles.chipActive]}>
          <Text style={[styles.chipText, fps === item && styles.chipTextActive]}>{item} FPS</Text>
        </Pressable>
      ))}</View>

      <View style={styles.note}><Sparkles size={16} color={lime} /><Text style={styles.noteText}>Provider-backed generation runs on the server. If credentials are unavailable, the app labels its local demo outputs.</Text></View>
      <Pressable style={[styles.submit, busy && { opacity: 0.7 }]} onPress={() => void create()} disabled={busy}>
        {busy ? <ActivityIndicator color="#151910" /> : <><Lightbulb size={17} color="#151910" /><Text style={styles.submitText}>Build my film</Text></>}
      </Pressable>
      <Text style={styles.fineprint}><FileText size={10} color="#7c837b" /> API secrets never leave the server</Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#101310' }, content: { paddingHorizontal: 22, paddingTop: 20, paddingBottom: 42 },
  back: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 29 }, backText: { color: '#a2a89f', fontFamily: 'SpaceGrotesk_600SemiBold', fontSize: 10, letterSpacing: 1.2 },
  eyebrow: { color: lime, fontFamily: 'SpaceGrotesk_700Bold', fontSize: 9, letterSpacing: 1.4 }, title: { color: '#f3f2eb', fontFamily: 'SpaceGrotesk_700Bold', fontSize: 38, lineHeight: 41, marginTop: 9 }, subtitle: { maxWidth: 310, color: '#a1a59c', fontFamily: 'SpaceGrotesk_400Regular', fontSize: 12, lineHeight: 18, marginTop: 10, marginBottom: 24 },
  field: { marginBottom: 20 }, label: { color: '#c4c8bd', fontFamily: 'SpaceGrotesk_700Bold', fontSize: 9, letterSpacing: 1.15, marginBottom: 9 }, labelLine: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, optional: { color: '#777f75', fontFamily: 'SpaceGrotesk_500Medium', fontSize: 8, letterSpacing: 0.8, marginBottom: 9 },
  input: { color: '#f1f0e9', backgroundColor: '#191e19', borderColor: '#2b312b', borderWidth: 1, borderRadius: 5, paddingHorizontal: 13, paddingVertical: 12, fontFamily: 'SpaceGrotesk_400Regular', fontSize: 13 }, storyInput: { minHeight: 148, lineHeight: 19, paddingTop: 12 }, optionInput: { marginTop: 0, marginBottom: 18 }, inputFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 }, counter: { color: '#6f766d', fontFamily: 'SpaceGrotesk_400Regular', fontSize: 9 }, importButton: { minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 6 }, importText: { color: lime, fontFamily: 'SpaceGrotesk_500Medium', fontSize: 10 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 4, borderWidth: 1, borderColor: '#333a32', backgroundColor: '#191e19' }, chipActive: { backgroundColor: lime, borderColor: lime }, chipText: { color: '#aeb3a9', fontFamily: 'SpaceGrotesk_500Medium', fontSize: 10 }, chipTextActive: { color: '#151910' }, frameChip: { minWidth: 56, alignItems: 'center' }, durationList: { gap: 7, paddingBottom: 20 }, durationChip: { minWidth: 54, alignItems: 'center', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 4, borderWidth: 1, borderColor: '#333a32', backgroundColor: '#191e19' },
  suggestButton: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 5 }, suggestText: { color: lime, fontFamily: 'SpaceGrotesk_600SemiBold', fontSize: 9 }, recommendation: { color: '#abb49f', fontFamily: 'SpaceGrotesk_400Regular', fontSize: 9, lineHeight: 14, marginTop: -13, marginBottom: 16 },
  note: { flexDirection: 'row', alignItems: 'flex-start', gap: 9, padding: 12, backgroundColor: '#1a2116', borderRadius: 5, marginTop: 1, marginBottom: 16 }, noteText: { flex: 1, color: '#b8c0ab', fontFamily: 'SpaceGrotesk_400Regular', fontSize: 10, lineHeight: 15 }, submit: { minHeight: 47, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 9, backgroundColor: lime, borderRadius: 5 }, submitText: { color: '#151910', fontFamily: 'SpaceGrotesk_700Bold', fontSize: 13 }, fineprint: { textAlign: 'center', color: '#777f75', fontFamily: 'SpaceGrotesk_500Medium', fontSize: 9, marginTop: 12 },
});